"""R84c Blind-B (or Blind-A) readiness preflight.

Checks that all artifacts needed for an R84c blind run are present. Reports
each missing item with the command to build it.

Usage:
  uv run python scripts/expR84c_blind_preflight.py --blind-name blind_a   # dry-run path
  uv run python scripts/expR84c_blind_preflight.py --blind-name blind_b   # production day
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


class Check:
    def __init__(self, label: str, path: Path | None, fix_cmd: str,
                 *, optional: bool = False, exists_fn=None):
        self.label = label
        self.path = path
        self.fix_cmd = fix_cmd
        self.optional = optional
        self.exists_fn = exists_fn

    def exists(self) -> bool:
        if self.exists_fn:
            return self.exists_fn()
        return self.path is not None and self.path.exists()

    def size_mb(self) -> str:
        if self.path and self.path.exists():
            return f"{self.path.stat().st_size/1e6:.1f} MB"
        return "—"


def env_has(*names) -> bool:
    return any(os.environ.get(n) for n in names)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--blind-name", default="blind_a",
                   choices=["blind_a", "blind_b"],
                   help="Which blind split to preflight for")
    p.add_argument("--colab-stage", action="store_true",
                   help="Print Colab commands needed if R84 5-fold ensemble missing")
    args = p.parse_args()

    bn = args.blind_name
    print(f"R84c blind preflight — target: {bn}")
    print("=" * 70)

    checks: list[Check] = []

    # --- Always-required: frozen LRs and case-features for production R84-LR ---
    checks.append(Check(
        "Frozen R54c LR",
        REPO / "cache" / "r54_phase3_lr_model.txt",
        "Produced by R54 phase3 production training. Cannot regenerate without R39 LR setup.",
    ))
    checks.append(Check(
        "Production R84c LR",
        REPO / "cache" / "r84c_production_lr.txt",
        "Produced by scripts/expR84c_blind_candidate.py (in train_production_r84_lr step). "
        "Will be auto-generated by replay if missing AND r84b case_features.pkl present.",
    ))
    checks.append(Check(
        "R84b case_features cache (R54-stacked pool, fp64)",
        REPO / "cache" / "r84b" / "case_features.pkl",
        "Re-run scripts/expR84b_sweep.py to rebuild (Mac, ~5 min).",
    ))

    # --- Modality cache (used by R85+ if revisited; not required by R84c itself) ---

    # --- Per-blind data: source cache, R54 blind lists, R84 5-fold blind lists ---
    src_cache = REPO / "cache" / bn / "source_cache.pkl"
    checks.append(Check(
        f"Source cache for {bn}",
        src_cache,
        f"For Blind-B: build with the existing inference pipeline "
        f"(run_inference_blind_{{r3_det,f1,r21}} etc.) that populates "
        f"cache/{bn}/source_cache/ and cache/{bn}/source_cache.pkl.",
    ))

    r54_blind = REPO / "cache" / "r54_production" / (
        "blind_r54_lists.json" if bn == "blind_a" else f"{bn}_r54_lists.json"
    )
    checks.append(Check(
        f"R54 5-fold blind ensemble lists for {bn}",
        r54_blind,
        f"For Blind-A: already shipped. For Blind-B: run "
        f"scripts/expR54_phase3_ensemble_blind.py with --blind-name {bn} after "
        f"R54 phase3 fold model checkpoints are restored to disk.",
    ))

    r84_blind_dir = REPO / "cache" / "r84"
    r84_blind_paths = {
        k: r84_blind_dir / f"{'phase0b_fold0' if k == 0 and bn == 'blind_a' else f'{bn}_blind_fold{k}' if bn != 'blind_a' else f'blind_fold{k}'}" / "blind_r84_lists.json"
        for k in range(5)
    }
    # Simpler: for blind_a we have blind_fold{0..4}; for blind_b we'd write to {bn}_blind_fold{k}
    if bn == "blind_a":
        r84_blind_paths = {k: r84_blind_dir / f"blind_fold{k}" / "blind_r84_lists.json"
                           for k in range(5)}
    else:
        r84_blind_paths = {k: r84_blind_dir / f"{bn}_blind_fold{k}" / "blind_r84_lists.json"
                           for k in range(5)}

    for fold_k, p_ in r84_blind_paths.items():
        checks.append(Check(
            f"R84 fold-{fold_k} blind retrieval for {bn}",
            p_,
            f"COLAB A100 STEP: train R84 fold-{fold_k} model from R84 Phase 0A "
            f"pair manifest, then run scripts/expR84_blind_encode.py "
            f"--model-dir <model> --output-path {p_.relative_to(REPO)} --blind-cache cache/{bn}/source_cache.pkl. "
            f"See docs/blind_b_r84c_runbook.md for the full Colab cell.",
        ))

    # --- Read-only inputs ---
    checks.append(Check(
        "R84 Phase 0A pair manifest (training data for R84 retrievers)",
        REPO / "cache" / "r84" / "phase0a" / "pair_manifest.parquet",
        "Force-shipped in git at commit cc32829. Should always be present.",
    ))
    checks.append(Check(
        "R84 Phase 0A build_config (manifest fingerprint)",
        REPO / "cache" / "r84" / "phase0a" / "build_config.json",
        "Committed alongside the manifest.",
    ))

    # --- API key for response generation ---
    checks.append(Check(
        "ANTHROPIC_API_KEY or ANTHROPIC_RECSYS_API_KEY in environment",
        None,
        "export ANTHROPIC_RECSYS_API_KEY=sk-... (or ANTHROPIC_API_KEY)",
        exists_fn=lambda: env_has("ANTHROPIC_API_KEY", "ANTHROPIC_RECSYS_API_KEY"),
    ))

    # --- HF cache (for catalog metadata + Track-Embeddings if R85+ revisited) ---
    hf_cache_arrow = (Path.home() / ".cache/huggingface/datasets/"
                       "talkpl-ai___talk_play_data-challenge-track-metadata")
    checks.append(Check(
        "HF Track-Metadata cache",
        None,
        "Run any script that calls load_catalog() — it auto-downloads.",
        exists_fn=lambda: hf_cache_arrow.exists() and any(hf_cache_arrow.rglob("*.arrow")),
    ))

    # --- R78 submission for Blind-A response reuse (only needed for Blind-A replay) ---
    if bn == "blind_a":
        checks.append(Check(
            "R78 blind submission (for unchanged-top1 response reuse on Blind-A)",
            REPO / "exp" / "inference" / "blind_a" / "r78_llm_polish_submission.zip",
            "Already shipped in git. Required for Blind-A replay parity (responses).",
        ))

    # --- Optional: R12 dev payload (for any margin/sanity work) ---
    checks.append(Check(
        "R12 dev payload (not strictly needed for blind; useful for debugging)",
        REPO / "exp" / "eval" / "_R12_all_turns_payload.pkl",
        "Build via scripts/expR84_phase0a_census.py or any dev-eval script.",
        optional=True,
    ))

    # --- Report ---
    print(f"\n{'OK':>3}  {'label':50s}  size")
    print("-" * 80)
    n_required_missing = 0
    n_optional_missing = 0
    missing_with_fix: list[Check] = []
    for c in checks:
        ok = c.exists()
        mark = "✓" if ok else ("○" if c.optional else "✗")
        print(f"  {mark}  {c.label:50s}  {c.size_mb()}")
        if not ok:
            if c.optional:
                n_optional_missing += 1
            else:
                n_required_missing += 1
                missing_with_fix.append(c)

    print("\n" + "=" * 70)
    if n_required_missing == 0:
        print(f"PREFLIGHT PASS for {bn}. {n_optional_missing} optional items missing.")
        sys.exit(0)
    else:
        print(f"PREFLIGHT FAIL: {n_required_missing} required artifact(s) missing.")
        print(f"\nFix commands (in order):")
        for c in missing_with_fix:
            print(f"\n  [missing] {c.label}")
            print(f"    {c.fix_cmd}")
        sys.exit(2)


if __name__ == "__main__":
    main()
